export default {
  close: 'Close',
  message: 'Message',
  minimize: 'Minimize',
  connecting: 'Connecting', 
  wait_for_mobile: 'Establishing connection. It can take up to 30 seconds. Please wait.',
  ringing: 'Ringing',
  hangup: 'Hang Up',
  voice_mail_title: 'Send Voice Message to',
  voice_mail_message: 'The person you are trying to call is currently unavailable. Would you like to send a voice message?',
  message_sent: 'Your voice message has been sent!',
  record_again: 'Record Again',
  yes_add: 'Yes',
  dont_add: 'No',
  incoming_call: 'Incoming Call',
  outgoing_call: 'Outgoing Call',
  answer: 'Answer',
  add_to_call: 'Add to Call',
  calling: 'Calling',
  recording: 'Recording...',
  play: 'Play',
  stop: 'Stop',
  send: 'Send',
  hide_chat: 'Hide Chat',
  chat: 'Chat',
  cancel: 'Cancel',
  ok: 'OK',
  add_to_call: 'Add',
  camera: 'Camera',
  volume: 'Volume',
  microphone: 'Microphone',
  camera_info: 'Camera Info',
  turn_off_camera: 'Turn Off Camera',
  share_screen: 'Share Screen',
  get_media_not_allowed: 'Your camera or microphone are not accessible. Please make sure that you allowed access to camera and microphone on your device and try again.',
  not_allowed_screensharing: 'Screen sharing is not allowed. Please make sure that you allowed access to your screen and try again.',
  chat_placeholder: 'Type your message',
  user_is_offline: 'is not online. Try again later.',
  you_are_offline: 'You are not online. Check your internet connection and try again.',
  already_in_call: 'You are already in call',
  at: 'at',
  missed_call: 'You missed call from',
  send_message: 'Send Message',
  send_av_message_title: 'Leave a Message?',
  send_av_message_desc: ' is currently not available. You can choose to leave him/her a voice or video message. The maximum message length is 60 seconds.',
  record_audio: 'Record Voice Message',
  record_audio_video: 'Record Video Message',
  start_recording: 'Start Recording',
  stop_recording: 'Stop Recording',
  processing_message_title: 'Processing Message',
  processing_message: 'Please wait while we process your message. You can close this dialog, but do not close this browser tab or navigate to another page. You will be notified when your message is ready.',
  message_uploaded: 'Your message is ready. Below is the message link that you can send to the message recipient.',
  message_link: 'Message Link',
  finalizing: 'Finalizing ...',
  uploading: 'Uploading ...',
  record_screen: 'Record Screen',
  screen_share_not_allowed: 'Your screen is not accessible. Please make sure that you allowed access to screen sharing on your device and try again.',
  init_remote_screensharing: 'Init remote screensharing',
  choose_contact: 'Choose Contact',
  mute_microphone: 'Mute microphone',
  phone_number: 'Phone number',
  message: 'Message',
  send_sms_message: 'Send SMS Message',
  send_sms_description: 'Enter a phone number of a person that you want to send a text message',
  sending_sms_msg: 'Sending SMS message. Please wait.',
  error_send_sms_msg: 'Error occured while sending text message.',
  sms_sent_success: 'Text messagge is sent successfully.',
  phone_and_message_required: 'Phone number and message are required!',
  call_phone_number: 'Call Phone Number',
  call_phone_number_desc: 'Enter a phone number of a person that you want to call',
  call_number: 'Call Number',
  call_number_error: 'Error occured while calling the number',
  calling_phone_number: 'Calling phone number',
  phone_number_required: 'Phone number is required!',
  room_name: 'Room name',
  room_name_required: 'Room name is required',
  create_conf_room: 'Create Conference Room',
  create_conf_room_msg: 'Enter room name and press "Get link" button in order to create room and get the link which you can share with others.',
  get_conf_room_link: 'Get Link',
  conf_room_error: 'An Error occured while creating a conference room.',
  conf_room_success: 'You successfully created conference room. Use link below to invite other participants.',
  not_connected_to_server: 'You are not connected to the rtc server',
  recording_not_supported: 'Your browser doesn\'t support recording media. Please try again in a different browser.',
  message_proccess_error: 'Error proccessing message. Please try again later.',
  error_get_quick_links: 'Error getting quick links.',
  error_delete_quick_links: 'Error deleting quick link.',
  no_quick_links: 'You don\'t have any quick links.',
  quick_link: 'Quick link',
  quick_links: 'Quick links',
  expires_on: 'Expires on',
  expired_on: 'Expired on',
  conference_room: 'Conference room',
  conference_rooms: 'Conference rooms',
  no_conf_rooms: 'You don\'t have any conference rooms',
  error_get_conf_rooms: 'Error getting conference rooms.',
  error_delete_conf_room: 'Error deleting conference room.',
  error_get_av_messages: 'Error getting media messages.',
  error_delete_av_message: 'Error deleting media message.',
  media_message: 'Media message',
  media_messages: 'Media messages',
  no_media_messages: 'You don\'t have any media messages.',
  start_cobrowsing: 'Start co-browsing',
  stop_cobrowsing: 'Stop co-browsing',
  cobrowsing_session_stopped: 'Co-browsing session stopped.',
  init_cobrowsing: 'Initialize co-browsing',
  waiting_for: 'Waiting for',
  to_accept_cobrowsing: 'to accept your request for co-browsing.',
  rejected_cobrowsing_request: 'rejected your request for co-browsing.',
  cobrowsing_request: 'Co-browsing request',
  cobrowsing_request_sent: ' sent you a request for co-browsing.',
  reject: 'Reject',
  ft_rejected: 'File transfer was rejected.',
  waiting_recipient: 'Waiting for the recipient...',
  sending_file: 'Sending file...',
  receiving_file: 'Receiving file...',
  done: 'Done',
  is_not_online: 'is not online',
  receive_file: 'Receive file',
  send_file: 'Send file',
  drag_and_drop_file: 'Drag and drop a file in this area or browse files from your device',
  accept: 'Accept',
  browse_files: 'Browse files',
  no_chat_messages: 'No messages in this conversations',
  hide_elements_title: 'Do you want to hide certain elements?' ,
  hide_elements_info: 'You can hide sensitive data like credit card number in co-browsing session. If you choose "Yes", you will be able to select elements on the page which you want to be hidden before starting co-browsing session.',
  hide_elements_yes: 'Yes',
  hide_elements_no: 'No',
  presence_state_names: {
    dnd: 'Do not disturb',
    away: 'Away',
    chat: 'Available',
    xa: 'Invisible'
  },
  presence: 'Presence',
  update_presence: 'Update presence',
  presence_state: 'State',
  presence_status: 'Status',
  user_not_available_for_call: 'is not available at the moment'
}