export default {
  close: 'Lukk',
  message: 'Melding',
  minimize: 'Minimer',
  connecting: 'Kobler til',
  wait_for_mobile: 'Oppkobling kan ta opptil 30 sekunder. Vennligst vent...',
  ringing: 'Ringer',
  hangup: 'Legg på',
  voice_mail_title: 'Send en talemelding til',
  voice_mail_message: 'Personen du prøver å ringe er for øyeblikket utilgjengelig. Vil du sende en talemelding?',
  message_sent: 'Din talemelding er sendt!',
  record_again: 'Spill inn på nytt',
  yes_add: 'Ja',
  dont_add: 'Nei',
  incoming_call: 'Innkommende samtale',
  outgoing_call: 'Utgående samtale',
  answer: 'Svar',
  calling: 'Ringer',
  recording: 'Spiller inn...',
  play: 'Spill av',
  stop: 'Stopp',
  send: 'Send',
  hide_chat: 'Skjul chat',
  chat: 'Chat',
  cancel: 'Avbryt',
  ok: 'OK',
  add_to_call: 'Legg til kontakt i samtalen',
  camera: 'Kamera',
  volume: 'Volum',
  microphone: 'Mikrofon',
  camera_info: 'Kamerainfo',
  turn_off_camera: 'Slå av kameraet',
  share_screen: 'Del skjerm',
  get_media_not_allowed: 'Kameraet eller mikrofonen din er ikke tilgjengelig. Vennligst sørg for at du har gitt tilgang til kameraet og mikrofonen på enheten din og prøv igjen.',
  not_allowed_screensharing: 'Skjermdeling er ikke tillatt. Vennligst sørg for at du har gitt tilgang til skjermen din og prøv igjen.',
  chat_placeholder: 'Skriv inn melding',
  user_is_offline: 'er ikke tilgjengelig. Prøv igjen senere.',
  you_are_offline: 'Du er ikke tilkoblet. Sjekk internettforbindelsen din og prøv igjen.',
  already_in_call: 'Du er allerede i samtalen',
  at: 'kl.',
  missed_call: 'Du har et tapt anrop fra',
  send_message: 'Send melding',
  send_av_message_title: 'Legg igjen en melding?',
  send_av_message_desc: 'er for øyeblikket ikke tilgjengelig. Du kan velge å legge igjen en tale- eller videomelding. Maksimal meldingslengde er 60 sekunder.',
  record_audio: 'Spill inn talemelding',
  record_audio_video: 'Spill inn videomelding',
  start_recording: 'Start opptak',
  stop_recording: 'Stopp opptak',
  processing_message_title: 'Behandler melding',
  processing_message: 'Vennligst vent mens vi behandler meldingen din. Du kan lukke dette vinduet, men ikke lukk nettleserfanen eller naviger til en annen side. Du vil bli varslet når meldingen din er klar.',
  message_uploaded: 'Meldingen din er klar. Nedenfor er meldingslenken som du kan sende til meldingsmottakeren.',
  message_link: 'Meldingslenke',
  finalizing: 'Fullfører...',
  uploading: 'Laster opp...',
  record_screen: 'Spill inn skjerm',
  screen_share_not_allowed: 'Skjermen din er ikke tilgjengelig. Vennligst sørg for at du har tillatt skjermdeling på enheten din og prøv igjen.',
  init_remote_screensharing: 'Start fjernstyring',
  choose_contact: 'Velg kontakt',
  mute_microphone: 'Demp mikrofon',
  phone_number: 'Telefonnummer',
  message: 'Melding',
  send_sms_message: 'Send tekstmelding',
  send_sms_description: 'Skriv inn telefonnummeret til personen du vil sende en tekstmelding til',
  sending_sms_msg: 'Sender tekstmelding. Vennligst vent.',
  error_send_sms_msg: 'Feil oppstod under sending av tekstmeldingen.',
  sms_sent_success: 'Tekstmeldingen er sendt.',
  phone_and_message_required: 'Telefonnummer og melding er påkrevd!',
  call_phone_number: 'Ring telefonnummer',
  call_phone_number_desc: 'Skriv inn telefonnummeret til personen du vil ringe',
  call_number: 'Ring nummer',
  call_number_error: 'Feil oppstod under oppringning',
  calling_phone_number: 'Ringer telefonnummer',
  phone_number_required: 'Telefonnummer er påkrevd!',
  room_name: 'Romnavn',
  room_name_required: 'Romnavn er påkrevd',
  create_conf_room: 'Opprett konferanserom',
  create_conf_room_msg: 'Skriv inn romnavn og trykk på "Få lenke" -knappen for å opprette rommet og få lenken som du kan dele med andre.',
  get_conf_room_link: 'Få lenke',
  conf_room_error: 'En feil oppstod under opprettelse av konferanserom.',
  conf_room_success: 'Du har opprettet et konferanserom. Bruk lenken nedenfor for å invitere de andre deltakerne.',
  not_connected_to_server: 'Du er ikke koblet til RTC-serveren',
  recording_not_supported: 'Nettleseren din støtter ikke medieopptak. Vennligst prøv igjen i en annen nettleser.',
  message_proccess_error: 'Feil ved behandling av melding. Vennligst prøv igjen senere.',
  error_get_quick_links: 'Feil ved henting av hurtiglenker.',
  error_delete_quick_links: 'Feil ved sletting av hurtiglenke.',
  no_quick_links: 'Du har ingen hurtiglenker.',
  quick_link: 'Hurtiglenke',
  quick_links: 'Hurtiglenker',
  expires_on: 'Utløper',
  expired_on: 'Utløpt',
  conference_room: 'Konferanserom',
  conference_rooms: 'Konferanserom',
  no_conf_rooms: 'Du har ingen konferanserom',
  error_get_conf_rooms: 'Feil ved henting av konferanserom.',
  error_delete_conf_room: 'Feil ved sletting av konferanserom.',
  error_get_av_messages: 'Feil ved henting av mediameldinger.',
  error_delete_av_message: 'Feil ved sletting av mediamelding.',
  media_message: 'Mediamelding',
  media_messages: 'Mediameldinger',
  no_media_messages: 'Du har ingen mediameldinger.',
  start_cobrowsing: 'Start skjermdeling',
  stop_cobrowsing: 'Stopp skjermdeling',
  cobrowsing_session_stopped: 'skjermdelingsøkt stoppet.',
  init_cobrowsing: 'Start skjermdeling',
  waiting_for: 'Venter på',
  to_accept_cobrowsing: 'for å godta forespørselen din om skjermdeling.',
  rejected_cobrowsing_request: 'avslo forespørselen din om skjermdeling.',
  cobrowsing_request: 'forespørsel om skjermdeling',
  cobrowsing_request_sent: ' sendte deg en forespørsel om skjermdeling.',
  cobrowsing_annotations: 'Annotasjoner',
  cobrowsing_rc_info: 'Den andre siden har overtatt kontrollen. Vennligst ikke skriv, rull eller klikk på siden, før kontrollen er gitt tilbake til deg.',
  cobrowsing_hidden_elements: 'Skjulte elementer',
  cobrowsing_hide_elements: 'Begynn å velge elementer på siden for å legge dem til i skjulte listen.',
  cobrowsing_rc: 'Fjernkontroll',
  reject: 'Avslå',
  ft_rejected: 'Filoverføringen ble avslått.',
  waiting_recipient: 'Venter på mottakeren ...',
  sending_file: 'Sender fil ...',
  receiving_file: 'Mottar fil ...',
  done: 'Ferdig',
  is_not_online: 'er ikke tilgjengelig',
  receive_file: 'Motta fil',
  send_file: 'Send fil',
  drag_and_drop_file: 'Dra og slipp en fil i dette området, eller bla gjennom filer fra enheten din',
  accept: 'Godta',
  browse_files: 'Bla gjennom filer',
  no_chat_messages: 'Ingen meldinger i denne samtalen',
  hide_elements_title: 'Vil du skjule visse elementer?',
  hide_elements_info: 'Du kan skjule sensitiv informasjon som kredittkortnummer i skjermdelingsøkten. Hvis du velger "Ja", kan du velge elementer på siden som du vil skjule før du starter skjermdelingsøkten.',
  hide_elements_yes: 'Ja',
  hide_elements_no: 'Nei',
  presence_state_names: {
      dnd: 'Ikke forstyrr',
      away: 'Borte',
      chat: 'Tilgjengelig',
      xa: 'Usynlig'
  },
  presence: 'Tilstedeværelse',
  update_presence: 'Oppdater tilstedeværelse',
  presence_state: 'Tilstand',
  presence_status: 'Status',
  user_not_available_for_call: 'er ikke tilgjengelig for øyeblikket',
  download_link: 'Last ned lenke',
  confroom_recording_available_msg: 'Opptak er tilgjengelig',
  go_to_meeting: 'Gå til konferanserommet',
  more_options: 'Flere alternativer',
  show_more_options: 'Vis flere alternativer',
  hide_more_options: 'Skjul flere alternativer',
  turn_on_your_camera: 'Slå på kameraet ditt',
  turn_off_your_camera: 'Slå av kameraet ditt',
  minimize_call: 'Minimer samtalen',
  maximize_call: 'Maksimer samtalen',
  hangup_this_call: 'Legg på denne samtalen',
  mute_your_mic: 'Demp mikrofonen din',
  unmute_your_mic: 'Slå på mikrofonen din',
  moving_to_conf_room: 'Flytter samtalen til konferanserommet.',
  please_wait: 'Vennligst vent ...',
  audio_video_settings: 'Innstillinger for lyd og video',
  stop_screen_share: 'Stopp skjermdeling',
  disabled_feature_error: 'Denne funksjonen er ikke aktivert for kontoen din, vennligst kontakt info@talaria.solutions for å aktivere den.',
  invalid_credentials: 'Ikke gyldig brukernavn eller passord. Vennligst sjekk konfigurasjonen din og prøv igjen.',
  conf_room_recordings_error: 'Feil ved henting av konferanseromopptak',
  media_recording_not_supported: 'Nettleseren din støtter ikke opptak av medier',
  start_remote_support_session: 'Start skjermdeling',
  start_remote_support_info: 'For å starte skjermdeling må du angi den 12-sifrede koden som du har fått fra kundekonsulenten din. Har du ikke fått en kode, må du snakke med Medlemssenteret først.',
  support_code_label: '12-sifret kode',
  support_code_placeholder: 'skriv inn koden her f.eks. 1234 5678 9101',
  support_code_button: 'Send',
  support_code_error: 'Det oppstod en feil, vennligst prøv igjen senere.',
  invalid_support_code: 'Koden du skrev inn er ikke gyldig. Vennligst sjekk koden og prøv igjen.',
  support_code_enabled: 'Skjermdeling aktivert',
  support_code_enabled_info: 'Du er klar til å godta skjermdeling. Koden din er {support_code}, og vil utløpe om {minutes} minutter.',
  remove_support_code: 'Avslutt økten og fjern koden',
  support_code: 'Koden',
  support_code_applied: 'er godkjent. Vennligst vent på kundekonsulent.' 
 }
 