export default {
  close: 'Zatvori',
  message: 'Poruka',
  minimize: 'Minimiziraj',
  connecting: 'Konektovanje',
  wait_for_mobile: 'Uspostavljanje konekcije može potrajati do 30 sekundi. Molim sačekajte...',
  ringing: 'Zvoni',
  hangup: 'Prekini',
  voice_mail_title: 'Pošalji glasovnu poruku',
  voice_mail_message: 'Osoba koju ste pokušali da pozovete trenutno nije dostupna. Da li želite da pošaljete glasovnu poruku?',
  message_sent: 'Vaša glasovna poruka je poslata!',
  record_again: 'Snimi ponovo',
  yes_add: 'Da',
  dont_add: 'Ne',
  incoming_call: 'Dolazni poziv',
  outgoing_call: 'Odlazni poziv',
  answer: 'Javi se',
  add_to_call: 'Dodaj u poziv',
  calling: 'Poziv',
  recording: 'Snimanje...',
  play: 'Pusti',
  stop: 'Zaustavi',
  send: 'Pošalji',
  hide_chat: 'Sakrij čet',
  chat: 'Čet',
  cancel: 'Odkaži',
  ok: 'OK',
  add_to_call: 'Dodaj',
  camera: 'Kamera',
  volume: 'Glasnoća',
  microphone: 'Mikrofon',
  camera_info: 'Informacije o kameri',
  turn_off_camera: 'Isključi kameru',
  share_screen: 'Podeli ekran',
  get_media_not_allowed: 'Vaša kamera i mikrofon nisu dostupni. Molimo proverite da li ste dozvolili pristup.',
  not_allowed_screensharing: 'Deljenje ekrana nije dozvoljeno.  Molimo dozvolite pristup i pokušajte ponovo.',
  chat_placeholder: 'Ovde piši poruku',
  user_is_offline: 'nije online. Pokušajte kasnije.',
  you_are_offline: 'Vi niste online. Proverite internet konekciju i pokušajte ponovo.',
  already_in_call: 'Već ste u pozivu',
  at: 'u',
  missed_call: 'Propušten poziv od',
  send_message: 'Pošalji poruku',
  send_av_message_title: 'Pošalji glasovnu ili video poruku',
  send_av_message_desc: 'nije trenutno online. Možete ostaviti glasovnu ili video poruku. Maksimalna dužina poruke je 60 sekundi.',
  record_audio: 'Snimi glasovnu poruku',
  record_audio_video: 'Snimi video poruku',
  start_recording: 'Počni snimanje',
  stop_recording: 'Završi snimanje',
  processing_message_title: 'Poruka se procesuira',
  processing_message: 'Molimo sačekajte dok pripremimo vašu poruku. Možete zatvoriti ovaj dijalog, ali nemojte zatvarati ovu stranicu. Obavestićemo vas kada poruka bude spremna.',
  message_uploaded: 'Vaša poruka je spremna. Dole je link koji možete poslati primaocu poruke.',
  message_link: 'Link do poruke',  
  finalizing: 'Pripremanje ...',
  uploading: 'Slanje ...',
  record_screen: 'Snimi ekran',
  screen_share_not_allowed: 'Deljenje ekrana nije dozvoljeno...',
  init_remote_screensharing: 'Pokreni deljenje ekrana kod sagovornika',
  choose_contact: 'Izaberi kontakt',
  mute_microphone: 'Mutiraj mikrofon',
  phone_number: 'Broj telefona',
  message: 'Poruka',
  send_sms_message: 'Pošalji SMS poruku',
  send_sms_description: 'Unesite broj telefona na koji želite da pošaljete SMS poruku',
  sending_sms_msg: 'Šaljemo SMS poruku. Molim sačekajte.',
  error_send_sms_msg: 'Greška prilikom slanja SMS poruke.',
  sms_sent_success: 'SMS poruka uspešno poslata.',
  phone_and_message_required: 'Morate uneti broj telefona i poruku.',
  call_phone_number: 'Pozovi broj telefona',
  call_phone_number_desc: 'Unesite broj telefona koji želite da pozovete',
  call_number: 'Pozovi broj',
  call_number_error: 'Greška prilikom pozivanja.',
  calling_phone_number: 'Pozivanje u toku...',
  phone_number_required: 'Morate uneti broj telefona.',
  room_name: 'Naziv sobe',
  room_name_required: 'Morate uneti naziv sobe',
  create_conf_room: 'Napravite sobu za konferenciju',
  create_conf_room_msg: 'Unesite ime sobe i kliknite na "Kreiraj link" dugme da bi dobili link koji možete da podelite.',
  get_conf_room_link: 'Kreiraj link',
  conf_room_error: 'Greška prilikom kreiranje sobe za konferenciju.',
  conf_room_success: 'Uspešno ste kreirali sobu za konferenciju. Link ispod možete da podelite sa učesnicima.',
  not_connected_to_server: 'Niste povezani na server.',
  recording_not_supported: 'Vaš brauzer ne podržava snimanje. Probajte u nekom drugom brauzeru.',
  message_proccess_error: 'Greška prilikom obrade poruke. Pokušajte kasnije.',
  error_get_quick_links: 'Greška prilikom generisanja linka za brzo pozivanje.',
  error_delete_quick_links: 'Greška prilikom brisanja linka za brzo pozivanje.',
  no_quick_links: 'Nemate ni jedan link za brzo pozivanje',
  quick_link: 'Link za brzo pozivanje',
  quick_links: 'Linkovi za brzo pozivanje',
  expires_on: 'Ističe',
  expired_on: 'Istekao je',
  conference_room: 'Soba za konferenciju',
  conference_rooms: 'Sobe za konferenciju',
  no_conf_rooms: 'Nemate ni jednu sobu za konferenciju.',
  error_get_conf_rooms: 'Greška prilikom preuzimanja liste soba za konferenciju.',
  error_delete_conf_room: 'Greška prilikom brisanja sobe za konferenciju.',
  error_get_av_messages: 'Greška prilikom preuzimanja liste video poruka.',
  error_delete_av_message: 'Greška prilikom brisanja video poruke.',
  media_message: 'Video poruka',
  media_messages: 'Video poruke',
  no_media_messages: 'Nemate ni jednu video poruku.',
  start_cobrowsing: 'Pokreni co-browsing',
  stop_cobrowsing: 'Zaustavi co-browsing',
  cobrowsing_session_stopped: 'Co-browsing sesija prekinuta.',
  init_cobrowsing: 'Inicijalizuj co-browsing',
  waiting_for: 'Čekam',
  to_accept_cobrowsing: 'da prihvati vaš zahtev za co-browsing',
  rejected_cobrowsing_request: 'je odbio vaš zahtev za co-browsing.',
  cobrowsing_request: 'Co-browsing zahtev',
  cobrowsing_request_sent: ' vam je poslao zahtev za co-browsing.',
  cobrowsing_annotations: 'Anotacije',
  cobrowsing_rc_info: 'Vaš sagovornik je preuzeo kontrolu. Molim vas, nemojte skolovati, pisati ili kliktati na stranici.',
  cobrowsing_hidden_elements: 'Skriveni elementi',
  cobrowsing_hide_elements: 'Selektujte elemente koje želite da sakrijete kod sagovornika.',
  cobrowsing_rc: 'Daljinska kontrola',
  reject: 'Odbij',
  ft_rejected: 'Prenos fajla je odbijen',
  waiting_recipient: 'Čekamo prihvatanje...',
  sending_file: 'Šaljem fajl...',
  receiving_file: 'Primam fajl...',
  done: 'Gotovo',
  is_not_online: 'nije online',
  receive_file: 'Prihvati fajl',
  send_file: 'Pošalji fajl',
  drag_and_drop_file: 'Prevucite fajl u ovu oblast ili prohnađite fajl na vašem uređaju.',
  accept: 'Prihvati',
  browse_files: 'Pronađi fajl',
  no_chat_messages: 'Nema poruka u ovoj konverzaciji.',
  hide_elements_title: 'Da li želite da sakrijete neke elemente na stranici?' ,
  hide_elements_info: 'Možete sakriti podatke kao što su brojevi kreditnih kartica u ovoj co-browsing sesiji. Ako odaberete "Da", moći će te da selektujete elemente koji će biti sakriveni u co-browsing sesiji.',
  hide_elements_yes: 'Da',
  hide_elements_no: 'Ne',
  presence_state_names: {
    dnd: 'Ne uznemiravaj',
    away: 'Odsutan',
    chat: 'Dostupan',
    xa: 'Nije dostupan'
  },
  presence: 'Prisustvo',
  update_presence: 'Podesi prisustvo',
  presence_state: 'Trenutno',
  presence_status_text: 'Status tekst',
  user_not_available_for_call: 'nije trenutno dostupan/dostupna',
  download_link: 'Link za preuzimanje',
  confroom_recording_available_msg: 'Snimak konferencijskog poziva je dostupan za preuzimanje',
  go_to_meeting: 'Pređi u sobu za konferencije',
  more_options: 'Dodatne opcije',
  show_more_options: 'Prikaži dodatne opcije',
  hide_more_options: 'Sakrij dodatne opcije',
  turn_on_your_camera: 'Uključi svoju kameru',
  turn_off_your_camera: 'Isključi svoju kameru',
  minimize_call: 'Smanji prozor poziva',
  maximize_call: 'Povećaj prozor poziva',
  hangup_this_call: 'Prekini ovaj poziv',
  mute_your_mic: 'Isključi mikrofon',
  unmute_your_mic: 'Uključi mikrofon',
  moving_to_conf_room: 'Poziv se prebaciju u konferencijski režim.',
  please_wait: 'Molimo sačekajte ...',
  audio_video_settings: 'Audio i video podešavanja',
  stop_screen_share: 'Prekini deljenje ekrana',
  disabled_feature_error: 'Ova funkcionalnost nije omogućena za vaš nalog. Kontaktirajte info@talaria.solutions da bi ste je omogućili.',
  invalid_credentials: 'Pogrešni kredencijali. Proverite kredencijale i pokušajte ponovo.',
  conf_room_recordings_error: 'Greška prilikom preuzimanja snimaka konferencijskih poziva.',
  media_recording_not_supported: 'Vaš pregledač ne podržava snimanje zvuka i video poziva.',
  start_remote_support_session: 'Pokreni sesiju za udaljenu podršku',
  start_remote_support_info: 'Molimo vas da unesete 12 cifreni kod koji ste dobili od našeg tima za podršku. Ako nemate kod, kontaktirajte našu korisničku podršku.',
  support_code_label: '12 cifreni kod za udaljenu podršku',
  support_code_placeholder: 'upišite kod ovde npr. 1234 5678 9101',
  support_code_button: 'Primeni kod',
  support_code_error: 'Greška prilikom primene koda. Molimo vas da proverite kod i pokušate ponovo.',
  invalid_support_code: 'Kod koji ste uneli nije validan. Molimo vas da proverite kod i pokušate ponovo.',
  support_code_enabled: 'Sesiija za udaljenu podršku je omogućena',
  support_code_enabled_info: 'Možete da prihvatite udaljenu podršku. Vaš kod je {support_code}, i isteći će za {minutes} minuta.',
  remove_support_code: 'Zaustavi sesiju i obriši kod',
  support_code: 'Kod',
  support_code_applied: 'je uspešno primenjen! Molim vas sačekajte da se agent pridruži sesiji.'
}