name: Deploy to S3

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1  

    - name: Sync directory to S3
      run: |
        aws s3 sync ./demo/ s3://tlr-static/demo/ --delete
      
    - name: Copy popup file to S3 root
      run: |
        aws s3 cp ./demo/popup.html s3://tlr-static/popup.html

    - name: Copy test file to S3 root
      run: |
        aws s3 cp ./demo/test.html s3://tlr-static/test.html
        
    - name: invalidate
      uses: chetan/invalidate-cloudfront-action@v2
      env:
        PATHS: '/popup.html /test.html /demo/*'
        AWS_REGION: 'eu-north-1'
        DISTRIBUTION: 'E1Z0VG7BSJRNKI'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
